// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCPLELSPifr7BSnjdxUT8Kj89w6SH72U',
    appId: '1:582823167228:web:78821324b2b21791558379',
    messagingSenderId: '582823167228',
    projectId: 'vaayo-app',
    authDomain: 'vaayo-app.firebaseapp.com',
    storageBucket: 'vaayo-app.appspot.com',
    measurementId: 'G-RHZ261QG2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7xdEoDYmtzJbBGEa9DiM4K-8Dq-b68Bg',
    appId: '1:582823167228:android:6790c60fe28b8d19558379',
    messagingSenderId: '582823167228',
    projectId: 'vaayo-app',
    storageBucket: 'vaayo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA59sxkfB9CIxPpGogQd3mJ6MJTW-n5_uo',
    appId: '1:582823167228:ios:3287d58705b17ba2558379',
    messagingSenderId: '582823167228',
    projectId: 'vaayo-app',
    storageBucket: 'vaayo-app.appspot.com',
    iosBundleId: 'com.example.vaayo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA59sxkfB9CIxPpGogQd3mJ6MJTW-n5_uo',
    appId: '1:582823167228:ios:c2002696453bbb35558379',
    messagingSenderId: '582823167228',
    projectId: 'vaayo-app',
    storageBucket: 'vaayo-app.appspot.com',
    iosBundleId: 'com.example.vaayo.RunnerTests',
  );
}
